// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: digests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRecentDigests = `-- name: GetRecentDigests :many
SELECT id, generated_at, sources_count, alerts_count, content, delivered
FROM digests
ORDER BY generated_at DESC
LIMIT $1
`

type GetRecentDigestsRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	GeneratedAt  pgtype.Timestamptz `db:"generated_at" json:"generated_at"`
	SourcesCount int32              `db:"sources_count" json:"sources_count"`
	AlertsCount  int32              `db:"alerts_count" json:"alerts_count"`
	Content      string             `db:"content" json:"content"`
	Delivered    bool               `db:"delivered" json:"delivered"`
}

func (q *Queries) GetRecentDigests(ctx context.Context, limit int32) ([]GetRecentDigestsRow, error) {
	rows, err := q.db.Query(ctx, getRecentDigests, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentDigestsRow{}
	for rows.Next() {
		var i GetRecentDigestsRow
		if err := rows.Scan(
			&i.ID,
			&i.GeneratedAt,
			&i.SourcesCount,
			&i.AlertsCount,
			&i.Content,
			&i.Delivered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDigestDelivered = `-- name: MarkDigestDelivered :exec
UPDATE digests
SET delivered = true, delivered_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkDigestDelivered(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markDigestDelivered, id)
	return err
}

const saveDigest = `-- name: SaveDigest :one
INSERT INTO digests (sources_count, alerts_count, content, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, generated_at
`

type SaveDigestParams struct {
	SourcesCount int32  `db:"sources_count" json:"sources_count"`
	AlertsCount  int32  `db:"alerts_count" json:"alerts_count"`
	Content      string `db:"content" json:"content"`
	Payload      []byte `db:"payload" json:"payload"`
}

type SaveDigestRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	GeneratedAt pgtype.Timestamptz `db:"generated_at" json:"generated_at"`
}

func (q *Queries) SaveDigest(ctx context.Context, arg SaveDigestParams) (SaveDigestRow, error) {
	row := q.db.QueryRow(ctx, saveDigest,
		arg.SourcesCount,
		arg.AlertsCount,
		arg.Content,
		arg.Payload,
	)
	var i SaveDigestRow
	err := row.Scan(&i.ID, &i.GeneratedAt)
	return i, err
}
