// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package db

import (
	"context"
)

const getLastSevenDays = `-- name: GetLastSevenDays :many
SELECT id, source, metric_date, revenue, failed_payments, created_at 
FROM daily_metrics
WHERE source = $1
AND metric_date >= NOW() - INTERVAL '7 days'
ORDER BY metric_date DESC
`

func (q *Queries) GetLastSevenDays(ctx context.Context, source string) ([]DailyMetric, error) {
	rows, err := q.db.Query(ctx, getLastSevenDays, source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyMetric{}
	for rows.Next() {
		var i DailyMetric
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.MetricDate,
			&i.Revenue,
			&i.FailedPayments,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
