// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DailyMetric struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	Source         string             `db:"source" json:"source"`
	MetricDate     pgtype.Date        `db:"metric_date" json:"metric_date"`
	Revenue        pgtype.Numeric     `db:"revenue" json:"revenue"`
	FailedPayments int32              `db:"failed_payments" json:"failed_payments"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Digest struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	Content           string             `db:"content" json:"content"`
	GeneratedAt       pgtype.Timestamptz `db:"generated_at" json:"generated_at"`
	HasCriticalAlerts bool               `db:"has_critical_alerts" json:"has_critical_alerts"`
}

type Snapshot struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Source      string             `db:"source" json:"source"`
	FetchedAt   pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
	Data        []byte             `db:"data" json:"data"`
	PeriodStart pgtype.Timestamptz `db:"period_start" json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `db:"period_end" json:"period_end"`
}
