// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DailyMetric struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Source     string             `db:"source" json:"source"`
	MetricDate pgtype.Date        `db:"metric_date" json:"metric_date"`
	Metrics    []byte             `db:"metrics" json:"metrics"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Digest struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	GeneratedAt  pgtype.Timestamptz `db:"generated_at" json:"generated_at"`
	SourcesCount int32              `db:"sources_count" json:"sources_count"`
	AlertsCount  int32              `db:"alerts_count" json:"alerts_count"`
	Content      string             `db:"content" json:"content"`
	Payload      []byte             `db:"payload" json:"payload"`
	Delivered    bool               `db:"delivered" json:"delivered"`
	DeliveredAt  pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
}

type Snapshot struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Source      string             `db:"source" json:"source"`
	FetchedAt   pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
	Data        []byte             `db:"data" json:"data"`
	PeriodStart pgtype.Timestamptz `db:"period_start" json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `db:"period_end" json:"period_end"`
}
