// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetLastSevenDays(ctx context.Context, source string) ([]DailyMetric, error)
	SaveDailyMetrics(ctx context.Context, arg SaveDailyMetricsParams) (DailyMetric, error)
	SaveDigest(ctx context.Context, arg SaveDigestParams) (Digest, error)
	SaveSnapshot(ctx context.Context, arg SaveSnapshotParams) (Snapshot, error)
}

var _ Querier = (*Queries)(nil)
