// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const saveDailyMetrics = `-- name: SaveDailyMetrics :one
INSERT INTO daily_metrics (source, metric_date, revenue, failed_payments)
VALUES ($1, $2, $3, $4)
RETURNING id, source, metric_date, revenue, failed_payments, created_at
`

type SaveDailyMetricsParams struct {
	Source         string         `db:"source" json:"source"`
	MetricDate     pgtype.Date    `db:"metric_date" json:"metric_date"`
	Revenue        pgtype.Numeric `db:"revenue" json:"revenue"`
	FailedPayments int32          `db:"failed_payments" json:"failed_payments"`
}

func (q *Queries) SaveDailyMetrics(ctx context.Context, arg SaveDailyMetricsParams) (DailyMetric, error) {
	row := q.db.QueryRow(ctx, saveDailyMetrics,
		arg.Source,
		arg.MetricDate,
		arg.Revenue,
		arg.FailedPayments,
	)
	var i DailyMetric
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.MetricDate,
		&i.Revenue,
		&i.FailedPayments,
		&i.CreatedAt,
	)
	return i, err
}

const saveDigest = `-- name: SaveDigest :one
INSERT INTO digests (content, has_critical_alerts)
VALUES ($1, $2)
RETURNING id, content, generated_at, has_critical_alerts
`

type SaveDigestParams struct {
	Content           string `db:"content" json:"content"`
	HasCriticalAlerts bool   `db:"has_critical_alerts" json:"has_critical_alerts"`
}

func (q *Queries) SaveDigest(ctx context.Context, arg SaveDigestParams) (Digest, error) {
	row := q.db.QueryRow(ctx, saveDigest, arg.Content, arg.HasCriticalAlerts)
	var i Digest
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.GeneratedAt,
		&i.HasCriticalAlerts,
	)
	return i, err
}

const saveSnapshot = `-- name: SaveSnapshot :one
INSERT INTO snapshots (source, data, period_start, period_end)
VALUES ($1, $2, $3, $4)
RETURNING id, source, fetched_at, data, period_start, period_end
`

type SaveSnapshotParams struct {
	Source      string             `db:"source" json:"source"`
	Data        []byte             `db:"data" json:"data"`
	PeriodStart pgtype.Timestamptz `db:"period_start" json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `db:"period_end" json:"period_end"`
}

func (q *Queries) SaveSnapshot(ctx context.Context, arg SaveSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRow(ctx, saveSnapshot,
		arg.Source,
		arg.Data,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.FetchedAt,
		&i.Data,
		&i.PeriodStart,
		&i.PeriodEnd,
	)
	return i, err
}
