// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshots.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRecentSnapshots = `-- name: GetRecentSnapshots :many
SELECT id, source, fetched_at, data, period_start, period_end
FROM snapshots
WHERE source = $1
    AND fetched_at >= NOW() - ($2::text || ' days')::INTERVAL
ORDER BY fetched_at DESC
`

type GetRecentSnapshotsParams struct {
	Source  string `db:"source" json:"source"`
	Column2 string `db:"column_2" json:"column_2"`
}

func (q *Queries) GetRecentSnapshots(ctx context.Context, arg GetRecentSnapshotsParams) ([]Snapshot, error) {
	rows, err := q.db.Query(ctx, getRecentSnapshots, arg.Source, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snapshot{}
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.FetchedAt,
			&i.Data,
			&i.PeriodStart,
			&i.PeriodEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveSnapshot = `-- name: SaveSnapshot :exec
INSERT INTO snapshots (source, data, period_start, period_end)
VALUES ($1, $2, $3, $4)
`

type SaveSnapshotParams struct {
	Source      string             `db:"source" json:"source"`
	Data        []byte             `db:"data" json:"data"`
	PeriodStart pgtype.Timestamptz `db:"period_start" json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `db:"period_end" json:"period_end"`
}

func (q *Queries) SaveSnapshot(ctx context.Context, arg SaveSnapshotParams) error {
	_, err := q.db.Exec(ctx, saveSnapshot,
		arg.Source,
		arg.Data,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	return err
}
